name: Deploy documentation

on:
  release:
    types: [ published ]
  push:
    branches:
      - master
      - feat-agrupate-ymls
      - dev*
env:
  VERSION_NAME: ${{ if github.event.release.tag_name != '' then github.event.release.tag_name else github.event.release.ref_name != '' then github.event.release.ref_name else 'latest' end }}


jobs:
  build_deploy:
    name: Build and deploy new release ${{ github.event.release.tag_name }}

    runs-on: self-hosted

    steps:
    - name: Show version
      run: |
        echo "Deploying version: ${{ env.VERSION_NAME }}"
        exit 1
