name: Deploy development branches

on:
  push:
    branches:
      - dev*

jobs:
  build_deploy:
    name: Build and deploy dev branch ${{ github.ref_name }}

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        echo "${GITHUB_WORKSPACE}/"
        cd "${GITHUB_WORKSPACE}/"
        pip3 install --user -r requirements.txt
    - name: Create new branch
      run: |
        echo "Creating new branch ${{ github.ref_name }}"
        mkdir -p /home/fmagalla/quasar/${{ github.ref_name }}
    - name: Parse legacy documentation
      run: |
        whoami
        cd "${GITHUB_WORKSPACE}/"
        ls -l ./docs/
        python3 ./docs/html2rst.py
    - name: Build documentation
      run: |
        cd "${GITHUB_WORKSPACE}/docs"
        make html
    - name: Update server
      run: |
        echo 'Change dir location to build html'
        cd "${GITHUB_WORKSPACE}/docs/build/html"

        echo 'Removing old build'
        rm -rf /home/fmagalla/quasar/${{ github.ref_name }}
        echo Enma19624 | sudo -S rm -rf /usr/share/nginx/quasar/${{ github.ref_name }}

        echo 'Creating new build'
        mkdir -p /home/fmagalla/quasar/${{ github.ref_name }}
        echo Enma19624 | sudo -S mkdir -p /usr/share/nginx/quasar/${{ github.ref_name }}

        echo 'Copying new build to local'
        cp -a . /home/fmagalla/quasar/${{ github.ref_name }}/

        echo 'Copying to nginx folder'
        sudo cp -r /home/fmagalla/quasar/${{ github.ref_name }} /usr/share/nginx/quasar

        echo 'Reloading nginx'
        echo Enma19624 | sudo -S nginx -s reload
