name: Deploy documentation

on:
  release:
    types: [ published ]
  push:
    branches:
      - master
      - dev*

jobs:

  build_deploy:
    name: Build and deploy documentation

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Define version name
      run: |
        if [ ${{ startsWith(github.ref_name, 'dev') }} = true ]; then
          echo "VERSION_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"
        elif [ ${{ github.event.release.tag_name != '' }} = true ]; then
          echo "VERSION_NAME=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"
        else
          echo "VERSION_NAME=latest" >> "$GITHUB_ENV"
        fi
        echo 'Version to build: ${{ env.VERSION_NAME }}'

    - name: Install dependencies
      run: |
        echo "${GITHUB_WORKSPACE}/"
        cd "${GITHUB_WORKSPACE}/"
        pip3 install --user -r requirements.txt

    - name: Create new folder
      run: |
        echo "Creating new folder ${{ env.VERSION_NAME }}"
        mkdir -p /home/fmagalla/quasar/${{ env.VERSION_NAME }}

    - name: Build HTML documentation
      run: |
        cd "${GITHUB_WORKSPACE}/docs"
        sphinx-build -b html ./source ./_build/${{ env.VERSION_NAME }}
    
    - name: Build documentation PDF as ePUB
      run: |
        cd "${GITHUB_WORKSPACE}/docs"

        make epub
        cp ./build/epub/Quasar.epub ./_build/${{ env.VERSION_NAME }}
        mv ./_build/${{ env.VERSION_NAME }}/Quasar.epub ./_build/${{ env.VERSION_NAME }}/Quasar\ ${{ env.VERSION_NAME }}.epub

        make latexpdf
        cp ./build/latex/quasar.pdf ./_build/${{ env.VERSION_NAME }}
        mv ./_build/${{ env.VERSION_NAME }}/quasar.pdf ./_build/${{ env.VERSION_NAME }}/Quasar\ ${{ env.VERSION_NAME }}.pdf

    - name: Update server
      run: |
        echo 'Change directory location to build html'
        cd "${GITHUB_WORKSPACE}/docs/_build/${{ env.VERSION_NAME }}"

        echo 'Removing old build'
        rm -rf /home/fmagalla/quasar/${{ env.VERSION_NAME }}
        echo ${{ secrets.PASS_USER }} | sudo -S rm -rf /usr/share/nginx/quasar/${{ env.VERSION_NAME }}

        echo 'Creating new build'
        mkdir -p /home/fmagalla/quasar/${{ env.VERSION_NAME }}
        echo ${{ secrets.PASS_USER }} | sudo -S mkdir -p /usr/share/nginx/quasar/${{ env.VERSION_NAME }}

        echo 'Copying new build to local'
        cp -a . /home/fmagalla/quasar/${{ env.VERSION_NAME }}/

        echo 'Copying to nginx folder'
        sudo cp -r /home/fmagalla/quasar/${{ env.VERSION_NAME }} /usr/share/nginx/quasar

        echo 'Reloading nginx'
        echo ${{ secrets.PASS_USER }} | sudo -S nginx -s reload

    - name: Update EOS page
      if: ${{ env.VERSION_NAME  == 'latest' }}
      run: |
        cd "${GITHUB_WORKSPACE}/docs/_build/${{ env.VERSION_NAME }}"
        
        echo 'Removing old build'
        echo ${{ secrets.PASS_USER }} | sudo -S rm -rf /eos/project-q/quasar/www

        echo 'Creating new build'
        echo ${{ secrets.PASS_USER }} | sudo -S mkdir -p /eos/project-q/quasar/www

        echo 'Copying new build to EOS
        cp -a . /eos/project-q/quasar/www
