name: Deploy documentation

on:
  release:
    types: [ published ]
  push:
    branches:
      - master
      - feat-agrupate-ymls
      - dev*

jobs:
  build_deploy:
    name: Build and deploy

    runs-on: self-hosted

    steps:
    - name: Define version
      run: |
        if [[ ${{ startsWith(github.ref_name, 'dev') }} ]]; then
          echo "VERSION_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"
        elif [[ ${{ startsWith(github.ref_name, 'feat-agrupate-ymls') }} ]]; then
          echo "VERSION_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"
        elif [[ ${{ github.event.release.tag_name != '' }} ]]; then
          echo "VERSION_NAME=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"
        else
          echo "VERSION_NAME=latest" >> "$GITHUB_ENV"
        fi
    - name: Show version
      run: |
        echo ${{ env.VERSION_NAME }}

